
library(spdep)
library(rgdal)
library(maptools)
library(sp)
library(RColorBrewer)
library(classInt)
library(GISTools)
library(maps)

library(RCurl)
library(tidyr)
library(ggplot2)
library(waffle)
library(rlist)
library(pdp)
library(corrplot)
library(dplyr)
library(caret)
library(stringr)
#library(data.table)
library(texreg)
library(spgwr)
library(factoextra)

library(spgwr)
#library(GWmodel) 
library(raster)
library(fossil)
library(flexclust) 
library(clusteval)
library(plot.matrix)
library(ape) 

library(shiny)
library(ggplot2)
library(ggpubr)
library(gridExtra)

library(plotly)
library(shinythemes)
library(shinyWidgets)
library(highcharter)

library(shiny)
library(plotly)
library(htmlwidgets)
library(highcharter)
library(bsplus)

