
library(spdep)
library(rgdal)
library(maptools)
library(sp)
library(RColorBrewer)
library(classInt)
library(GISTools)
library(maps)

library(RCurl)
library(tidyr)
library(ggplot2)
library(waffle)
library(rlist)
library(pdp)
library(corrplot)
library(dplyr)
library(caret)
library(stringr)
#library(data.table)
library(texreg)
library(spgwr)
library(factoextra)